/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetWaveDAO__factory } from "./BetWaveDAO__factory";
export { BetWaveOrganizer__factory } from "./BetWaveOrganizer__factory";
export { SimpleBet__factory } from "./SimpleBet__factory";
