/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetWaveDAO } from "./BetWaveDAO";
export type { BetWaveOrganizer } from "./BetWaveOrganizer";
export type { SimpleBet } from "./SimpleBet";
