/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleBetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beginEventTimestamp"
      | "betName"
      | "betWaveDaoAddress"
      | "betWavesOrganizerAddress"
      | "bettors"
      | "calculateValidatorReward"
      | "competitors"
      | "endEventTimestamp"
      | "redeemToBettor"
      | "sendPlatfromAndCreatorFees"
      | "sendValidatorFees"
      | "setBet"
      | "setFeesBooleanToTrue"
      | "setWinnerId"
      | "totalBet"
      | "winnerId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "newBid"): EventFragment;

  encodeFunctionData(
    functionFragment: "beginEventTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "betName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "betWaveDaoAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "betWavesOrganizerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bettors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateValidatorReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "competitors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endEventTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemToBettor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendPlatfromAndCreatorFees",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendValidatorFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeesBooleanToTrue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWinnerId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalBet", values?: undefined): string;
  encodeFunctionData(functionFragment: "winnerId", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "beginEventTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "betName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "betWaveDaoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "betWavesOrganizerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bettors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateValidatorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "competitors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endEventTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemToBettor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendPlatfromAndCreatorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendValidatorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeesBooleanToTrue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWinnerId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winnerId", data: BytesLike): Result;
}

export namespace newBidEvent {
  export type InputTuple = [
    arg0: AddressLike,
    arg1: BigNumberish,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BigNumberish,
    arg5: BigNumberish,
    arg6: BigNumberish
  ];
  export type OutputTuple = [
    arg0: string,
    arg1: bigint,
    arg2: bigint,
    arg3: bigint,
    arg4: bigint,
    arg5: bigint,
    arg6: bigint
  ];
  export interface OutputObject {
    arg0: string;
    arg1: bigint;
    arg2: bigint;
    arg3: bigint;
    arg4: bigint;
    arg5: bigint;
    arg6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleBet extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleBet;
  waitForDeployment(): Promise<this>;

  interface: SimpleBetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beginEventTimestamp: TypedContractMethod<[], [bigint], "view">;

  betName: TypedContractMethod<[], [string], "view">;

  betWaveDaoAddress: TypedContractMethod<[], [string], "view">;

  betWavesOrganizerAddress: TypedContractMethod<[], [string], "view">;

  bettors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        bettorAddress: string;
        betId: bigint;
        bettingAmout: bigint;
        bettingReward: bigint;
      }
    ],
    "view"
  >;

  calculateValidatorReward: TypedContractMethod<
    [_validatorFees: BigNumberish],
    [bigint],
    "view"
  >;

  competitors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        odd: bigint;
        betNumber: bigint;
        betAmount: bigint;
      }
    ],
    "view"
  >;

  endEventTimestamp: TypedContractMethod<[], [bigint], "view">;

  redeemToBettor: TypedContractMethod<[], [void], "payable">;

  sendPlatfromAndCreatorFees: TypedContractMethod<
    [
      _plateformeFees: BigNumberish,
      _creatorFees: BigNumberish,
      _ownerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  sendValidatorFees: TypedContractMethod<
    [_validatorAddress: AddressLike, _validatorReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBet: TypedContractMethod<[_betId: BigNumberish], [void], "payable">;

  setFeesBooleanToTrue: TypedContractMethod<[], [void], "nonpayable">;

  setWinnerId: TypedContractMethod<
    [_winnerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalBet: TypedContractMethod<[], [bigint], "view">;

  winnerId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beginEventTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "betName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "betWaveDaoAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "betWavesOrganizerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bettors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        bettorAddress: string;
        betId: bigint;
        bettingAmout: bigint;
        bettingReward: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateValidatorReward"
  ): TypedContractMethod<[_validatorFees: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "competitors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        odd: bigint;
        betNumber: bigint;
        betAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "endEventTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "redeemToBettor"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "sendPlatfromAndCreatorFees"
  ): TypedContractMethod<
    [
      _plateformeFees: BigNumberish,
      _creatorFees: BigNumberish,
      _ownerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendValidatorFees"
  ): TypedContractMethod<
    [_validatorAddress: AddressLike, _validatorReward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBet"
  ): TypedContractMethod<[_betId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "setFeesBooleanToTrue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWinnerId"
  ): TypedContractMethod<[_winnerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "winnerId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "newBid"
  ): TypedContractEvent<
    newBidEvent.InputTuple,
    newBidEvent.OutputTuple,
    newBidEvent.OutputObject
  >;

  filters: {
    "newBid(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      newBidEvent.InputTuple,
      newBidEvent.OutputTuple,
      newBidEvent.OutputObject
    >;
    newBid: TypedContractEvent<
      newBidEvent.InputTuple,
      newBidEvent.OutputTuple,
      newBidEvent.OutputObject
    >;
  };
}
