// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BetWaveDAO$Type } from "./BetWaveDAO";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BetWaveDAO"]: BetWaveDAO$Type;
    ["contracts/BetWaveDAO.sol:BetWaveDAO"]: BetWaveDAO$Type;
  }
}
