/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BetWaveDAO } from "./BetWaveDAO";
export type { BetWaveOrganizer } from "./BetWaveOrganizer";
export type { SimpleBet } from "./SimpleBet";
export * as factories from "./factories";
export { BetWaveDAO__factory } from "./factories/BetWaveDAO__factory";
export { BetWaveOrganizer__factory } from "./factories/BetWaveOrganizer__factory";
export { SimpleBet__factory } from "./factories/SimpleBet__factory";
